server {
  listen 8080;
  server_name _;
  resolver 127.0.0.11 valid=10s ipv6=off;
  set $event_hunter_api_upstream event-hunter-api:8080;
  set $event_lab_api_upstream event-lab:28343;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://$event_hunter_api_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /scenario-api/ {
    rewrite ^/scenario-api/(.*)$ /$1 break;
    proxy_pass http://$event_lab_api_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
