#!/usr/bin/env python3
"""Generate the immutable Check Model registry artifact from contracts/check-models/*.yaml."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MODEL_DIR = PROJECT_ROOT / "contracts" / "check-models"
OUTPUT = PROJECT_ROOT / "contracts" / "generated" / "check-model-registry.json"
GO_OUTPUT = (
    PROJECT_ROOT
    / "backend"
    / "internal"
    / "contexts"
    / "eventcheck"
    / "domain"
    / "registry_generated.go"
)


def registry_document() -> dict[str, object]:
    models: list[dict[str, object]] = []
    for path in sorted(MODEL_DIR.glob("*.yaml")):
        raw = path.read_bytes()
        model = yaml.safe_load(raw.decode("utf-8"))
        model.pop("$schema", None)
        models.append(
            {
                "source_path": path.relative_to(PROJECT_ROOT).as_posix(),
                "checksum": hashlib.sha256(raw).hexdigest(),
                "model": model,
            }
        )
    return {"registry_contract_version": 1, "models": models}


def render_registry() -> str:
    return json.dumps(registry_document(), ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_go_registry() -> str:
    payload = json.dumps(registry_document(), ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    return (
        "// Code generated by scripts/generate-check-model-registry.py; DO NOT EDIT.\n"
        "\n"
        "package domain\n"
        "\n"
        f"const generatedCheckModelRegistryJSON = `{payload}`\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated JSON is stale")
    parser.add_argument("--stdout", action="store_true", help="print generated JSON")
    args = parser.parse_args()
    rendered = render_registry()
    rendered_go = render_go_registry()
    if args.stdout:
        print(rendered, end="")
        return 0
    if args.check:
        stale = []
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            stale.append(OUTPUT.relative_to(PROJECT_ROOT).as_posix())
        if not GO_OUTPUT.is_file() or GO_OUTPUT.read_text(encoding="utf-8") != rendered_go:
            stale.append(GO_OUTPUT.relative_to(PROJECT_ROOT).as_posix())
        if stale:
            print(f"STALE {', '.join(stale)}")
            return 1
        print(
            "OK generated_check_model_registry="
            f"{OUTPUT.relative_to(PROJECT_ROOT)},{GO_OUTPUT.relative_to(PROJECT_ROOT)}"
        )
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    GO_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    GO_OUTPUT.write_text(rendered_go, encoding="utf-8")
    print(f"WROTE {OUTPUT.relative_to(PROJECT_ROOT)} {GO_OUTPUT.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
