#!/usr/bin/env python3
"""Generate the immutable Go Pattern Registry from contracts/patterns/*.yaml."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[1]
PATTERN_DIR = PROJECT_ROOT / "contracts" / "patterns"
OUTPUT = PROJECT_ROOT / "backend" / "internal" / "contexts" / "investigation" / "domain" / "patterns" / "registry_generated.go"


def registry_data() -> list[dict[str, object]]:
    result: list[dict[str, object]] = []
    for path in sorted(PATTERN_DIR.glob("*.yaml")):
        raw = path.read_bytes()
        pattern = yaml.safe_load(raw)
        fixtures = pattern.get("fixtures", {})
        match_count = len(fixtures.get("matches", []))
        non_match_count = len(fixtures.get("does_not_match", []))
        result.append(
            {
                "id": pattern["id"],
                "version": pattern["version"],
                "name": pattern["title"],
                "condition": pattern["description"],
                "severity": pattern["finding"]["matched_severity"],
                "window": pattern["expected"]["within"],
                "required_event_types": [pattern["trigger"]["event_type"]],
                "expected_event_types": [pattern["expected"]["event_type"]],
                "exclusion_event_types": pattern["exclusions"]["any_event_type"],
                "evidence_query_template_id": pattern["finding"]["query_template_id"],
                "status": str(pattern["status"]).upper(),
                "mutable_at_runtime": bool(pattern["implementation"]["mutable_at_runtime"]),
                "source_path": str(path.relative_to(PROJECT_ROOT)),
                "checksum": hashlib.sha256(raw).hexdigest(),
                "fixture_coverage": {
                    "match_count": match_count,
                    "non_match_count": non_match_count,
                    "total": match_count + non_match_count,
                },
                "trigger_event_type": pattern["trigger"]["event_type"],
                "expected_event_type": pattern["expected"]["event_type"],
                "matched_condition_codes": pattern["finding"]["matched_condition_codes"],
                "recommended_next_query": pattern["finding"]["recommended_next_query"],
            }
        )
    return result


def render_registry() -> str:
    payload = json.dumps(registry_data(), ensure_ascii=False, separators=(",", ":"))
    return (
        "// Code generated by scripts/generate-pattern-registry.py from contracts/patterns/*.yaml; DO NOT EDIT.\n"
        "\n"
        "package patterns\n"
        "\n"
        f"const generatedRegistryJSON = `{payload}`\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated Go is stale")
    parser.add_argument("--stdout", action="store_true", help="print generated Go")
    args = parser.parse_args()
    rendered = render_registry()
    if args.stdout:
        print(rendered, end="")
        return 0
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"STALE {OUTPUT.relative_to(PROJECT_ROOT)}")
            return 1
        print(f"OK generated_pattern_registry={OUTPUT.relative_to(PROJECT_ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"WROTE {OUTPUT.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
