#!/usr/bin/env python3
"""Generate the immutable Go Journey Profile Registry from contracts/journeys/*.yaml."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[1]
PROFILE_DIR = PROJECT_ROOT / "contracts" / "journeys"
OUTPUT = (
    PROJECT_ROOT
    / "backend"
    / "internal"
    / "contexts"
    / "investigation"
    / "domain"
    / "journeys"
    / "registry_generated.go"
)


def registry_data() -> list[dict[str, object]]:
    result: list[dict[str, object]] = []
    for path in sorted(PROFILE_DIR.glob("*.yaml")):
        raw = path.read_bytes()
        profile = yaml.safe_load(raw.decode("utf-8"))
        profile.pop("$schema", None)
        profile["source_path"] = path.relative_to(PROJECT_ROOT).as_posix()
        profile["checksum"] = hashlib.sha256(raw).hexdigest()
        result.append(profile)
    return result


def render_registry() -> str:
    payload = json.dumps(registry_data(), ensure_ascii=False, separators=(",", ":"))
    return (
        "// Code generated by scripts/generate-journey-registry.py from contracts/journeys/*.yaml; DO NOT EDIT.\n"
        "\n"
        "package journeys\n"
        "\n"
        f"const generatedRegistryJSON = `{payload}`\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated Go is stale")
    parser.add_argument("--stdout", action="store_true", help="print generated Go")
    args = parser.parse_args()
    rendered = render_registry()
    if args.stdout:
        print(rendered, end="")
        return 0
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"STALE {OUTPUT.relative_to(PROJECT_ROOT)}")
            return 1
        print(f"OK generated_journey_registry={OUTPUT.relative_to(PROJECT_ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"WROTE {OUTPUT.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
